name: Build and Deploy Cloud Run

on:
  push:
    branches:
      - main
      - test
      - dev

jobs:

  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v4

    - name: 'Setup Node 20 LTS'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: 'Configure build secrets'
      run: |
        echo '${{ secrets.BUILD_SECRET }}' > .env

    - name: 'Build project'
      run: |
        npm install typescript -g
        npm install
        npm run build

    - name: 'Build project - Upload artifact'
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: |
          dist
          package.json
          package-lock.json
        retention-days: 15
        include-hidden-files: true
        if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      WIF_PROVIDER: WIF_PROVIDER_IS_${{ github.ref_name }}
      WIF_SERVICE_ACCOUNT: WIF_SERVICE_ACCOUNT_IS_${{ github.ref_name }}

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v4

    - name: 'Build project - Download artifact'
      uses: actions/download-artifact@v4
      with:
        name: artifact

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ secrets[env.WIF_PROVIDER] }}'
        service_account: '${{ secrets[env.WIF_SERVICE_ACCOUNT] }}'

    - name: 'Set up Docker Buildx'
      uses: 'docker/setup-buildx-action@v3'

    - name: 'Login to GCR'
      uses: 'docker/login-action@v3'
      with:
        registry: us-docker.pkg.dev
        username: oauth2accesstoken
        password: '${{ steps.auth.outputs.access_token }}'

    - name: 'Docker Build and Push'
      uses: 'docker/build-push-action@v5'
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: 'us-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/${{ github.event.repository.name }}:${{ github.sha }}'

    - id: 'deploy'
      name: 'Deploy Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        image: 'us-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/${{ github.event.repository.name }}:${{ github.sha }}'
        service: 'is-cr-${{ github.event.repository.name }}'
        region: '${{ secrets.GCP_REGION }}'

    - name: 'Cloud Run URL'
      run: 'echo "${{ steps.deploy.outputs.url }}"'
